/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface SlotTestChild {
    'name': string;
  }
  interface SlotTestEmptyHostInner {}
  interface SlotTestEmptyHostOuter {}
  interface SlotTestInner {}
  interface SlotTestOuter {}
}

declare global {


  interface HTMLSlotTestChildElement extends Components.SlotTestChild, HTMLStencilElement {}
  var HTMLSlotTestChildElement: {
    prototype: HTMLSlotTestChildElement;
    new (): HTMLSlotTestChildElement;
  };

  interface HTMLSlotTestEmptyHostInnerElement extends Components.SlotTestEmptyHostInner, HTMLStencilElement {}
  var HTMLSlotTestEmptyHostInnerElement: {
    prototype: HTMLSlotTestEmptyHostInnerElement;
    new (): HTMLSlotTestEmptyHostInnerElement;
  };

  interface HTMLSlotTestEmptyHostOuterElement extends Components.SlotTestEmptyHostOuter, HTMLStencilElement {}
  var HTMLSlotTestEmptyHostOuterElement: {
    prototype: HTMLSlotTestEmptyHostOuterElement;
    new (): HTMLSlotTestEmptyHostOuterElement;
  };

  interface HTMLSlotTestInnerElement extends Components.SlotTestInner, HTMLStencilElement {}
  var HTMLSlotTestInnerElement: {
    prototype: HTMLSlotTestInnerElement;
    new (): HTMLSlotTestInnerElement;
  };

  interface HTMLSlotTestOuterElement extends Components.SlotTestOuter, HTMLStencilElement {}
  var HTMLSlotTestOuterElement: {
    prototype: HTMLSlotTestOuterElement;
    new (): HTMLSlotTestOuterElement;
  };
  interface HTMLElementTagNameMap {
    'slot-test-child': HTMLSlotTestChildElement;
    'slot-test-empty-host-inner': HTMLSlotTestEmptyHostInnerElement;
    'slot-test-empty-host-outer': HTMLSlotTestEmptyHostOuterElement;
    'slot-test-inner': HTMLSlotTestInnerElement;
    'slot-test-outer': HTMLSlotTestOuterElement;
  }
}

declare namespace LocalJSX {
  interface SlotTestChild {
    'name'?: string;
  }
  interface SlotTestEmptyHostInner {}
  interface SlotTestEmptyHostOuter {}
  interface SlotTestInner {}
  interface SlotTestOuter {}

  interface IntrinsicElements {
    'slot-test-child': SlotTestChild;
    'slot-test-empty-host-inner': SlotTestEmptyHostInner;
    'slot-test-empty-host-outer': SlotTestEmptyHostOuter;
    'slot-test-inner': SlotTestInner;
    'slot-test-outer': SlotTestOuter;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'slot-test-child': LocalJSX.SlotTestChild & JSXBase.HTMLAttributes<HTMLSlotTestChildElement>;
      'slot-test-empty-host-inner': LocalJSX.SlotTestEmptyHostInner & JSXBase.HTMLAttributes<HTMLSlotTestEmptyHostInnerElement>;
      'slot-test-empty-host-outer': LocalJSX.SlotTestEmptyHostOuter & JSXBase.HTMLAttributes<HTMLSlotTestEmptyHostOuterElement>;
      'slot-test-inner': LocalJSX.SlotTestInner & JSXBase.HTMLAttributes<HTMLSlotTestInnerElement>;
      'slot-test-outer': LocalJSX.SlotTestOuter & JSXBase.HTMLAttributes<HTMLSlotTestOuterElement>;
    }
  }
}


